-- DATA OVERVIEW AND BASIC EXPLORATION
-- Number of Unique Customers.
select count(distinct Customer_ID) as unique_customers from ecommerce_cleaned;

-- Find the minimum, maximum, and average total_amount.
select min(Total_Amount) as minimum_amount, 
max(Total_Amount) as maximum_amount, 
round(avg(Total_Amount),2) as avg_amount 
from ecommerce_cleaned;

-- Total revenue generated by each product category.
select Product_Category, round(sum(Total_Amount),2) as total_revenue 
from ecommerce_cleaned 
group by Product_Category 
order by total_revenue desc;

-- Average rating for each product category.
select Product_Category, round(avg(Customer_Rating),2) as avg_rating
from ecommerce_cleaned
group by Product_Category
order by avg_rating desc;

-- Average spending by age group.
select Age_Group, round(avg(Total_Amount),2) as avg_spending 
from ecommerce_cleaned
group by Age_Group
order by avg_spending desc;

-- Count the number of purchases made in each year.
select Year, count(*) as total_purchases
from ecommerce_cleaned
group by Year
order by Year;

-- REVENUE ANALYSIS
-- Total revenue generated by each gender.
select Gender, round(sum(Total_Amount),2) as total_revenue 
from ecommerce_cleaned 
group by Gender 
order by total_revenue desc;

-- Top 5 customers by total spending.
select Customer_ID, round(sum(Total_Amount),2) as total_spending
from ecommerce_cleaned
group by Customer_ID
order by total_spending desc
limit 5;

-- Average spending per customer and rank customers by it.
select Customer_ID, round(avg(Total_Amount),2) as avg_total_spending,
rank() over (order by avg(Total_Amount) desc) as spending_rank
from ecommerce_cleaned
group by Customer_ID
order by spending_rank;

-- Rank customers based on their total spending (highest to lowest).
select Customer_ID, round(sum(Total_Amount),2) as total_spending,
rank() over (order by sum(Total_Amount) desc) as spending_rank
from ecommerce_cleaned
group by Customer_ID;

-- Rank device types based on total revenue.
select Device_Type, round(sum(Total_Amount),2) as total_revenue,
rank() over (order by sum(Total_Amount) desc) as rn
from ecommerce_cleaned
group by Device_Type
order by rn; 

-- Total revenue generated by returning vs new customers.
select Is_Returning_Customer, round(sum(Total_Amount),2) as total_revenue
from ecommerce_cleaned
group by Is_Returning_Customer;

-- Average order value for discounted vs non-discounted orders.
select round(avg(Total_Amount),2) as avg_order_value, Discount_Applied
from ecommerce_cleaned
group by Discount_Applied;

-- Identify whether discounted orders or non discounted orders generate higher average ratings.
select Discount_Applied, avg(Customer_Rating) as avg_rating
from ecommerce_cleaned
group by Discount_Applied
order by avg_rating desc;

-- Find the top 5 cities by total revenue.
select City, round(sum(Total_Amount),2) as total_revenue
from ecommerce_cleaned
group by City
order by total_revenue desc
limit 5;

-- Identify the rating group that contributes the highest revenue.
select round(sum(Total_Amount),2) as highest_revenue, Customer_Rating
from ecommerce_cleaned
group by Customer_Rating
order by highest_revenue desc
limit 1;

-- Total revenue for each city where average customer rating > 3.
select City, round(sum(Total_Amount),2) as total_revenue, 
round(avg(Customer_Rating), 2) as avg_rating
from ecommerce_cleaned
group by City
having avg_rating > 3
order by avg_rating, total_revenue desc;

-- Top 3 cities by revenue for highly rated purchases (rating ≥ 3).
select City, round(sum(Total_Amount),2) as high_rating_revenue
from ecommerce_cleaned
where Customer_Rating >= 3
group by City
order by high_rating_revenue desc
limit 3;

-- CUSTOMER BEHAVIOR AND SEGMENTATION
-- Find the number of purchases made by each payment method.
select Payment_Method, count(*) as total_purchases
from ecommerce_cleaned
group by Payment_Method
order by total_purchases desc;

-- Top device type used by returning customers.
select Device_Type, count(*) as total_purchases
from ecommerce_cleaned
where Is_Returning_Customer = 1
group by Device_Type
order by total_purchases desc;

-- Find repeat customers (customers with purchase count > 1).
select Customer_ID, count(*) as purchase_count
from ecommerce_cleaned
group by Customer_ID
having purchase_count > 1
order by purchase_count desc;

-- Identify the best-performing combination of device type and discount usage.
select Device_Type, Discount_Applied, round(sum(Total_Amount),2) as total_revenue
from ecommerce_cleaned
group by Device_Type, Discount_Applied
order by total_revenue desc
limit 5;

-- Total number of purchases made from each device type.
select Device_Type, count(*) as total_purchases 
from ecommerce_cleaned
group by Device_Type;

-- Cities where the average customer rating is greater than or equal to 3.
select City, avg(Customer_Rating) as avg_rating
from ecommerce_cleaned
group by City
having avg_rating >= 3
order by avg_rating desc;

-- Find whether returning customers give higher ratings than new customers.
select Is_Returning_Customer, round(avg(Customer_Rating),2) as avg_rating
from ecommerce_cleaned
group by Is_Returning_Customer
order by avg_rating desc;

-- TIME BASED ANALYSIS
-- Month-wise total revenue.
select Month_Name, round(sum(Total_Amount),2) as total_revenue 
from ecommerce_cleaned
group by Month_Name
order by total_revenue desc;

-- Year with the maximum number of purchases.
select Year, count(*) as total_purchases
from ecommerce_cleaned
group by Year
order by total_purchases desc
limit 1;

-- Year-wise revenue split between new and returning customers.
select Year, Is_Returning_Customer, round(sum(Total_Amount),2) as total_revenue
from ecommerce_cleaned
group by Year, Is_Returning_Customer
order by total_revenue desc;

-- Identify the month with the highest revenue.
select Month_Name, round(sum(Total_Amount),2) as total_revenue  
from ecommerce_cleaned
group by Month_Name
order by total_revenue desc
limit 1;

-- Find the average monthly revenue for each year.
select Year, round(avg(monthly_revenue), 2) as avg_monthly_revenue
from (
    select Year, Month_Name, sum(total_amount) as monthly_revenue
    from ecommerce_cleaned
    group by Year, Month_Name
) t
group by Year
order by Year;

-- ADVANCED SQL
-- Top 3 product categories by total revenue for each gender.
with ranked_orders as (
	select Product_Category, Gender, round(sum(Total_Amount),2) as total_revenue
    from ecommerce_cleaned
    group by Product_Category, Gender), 
    ranked_category as (
		select Product_Category, Gender, total_revenue,
        row_number() over (partition by Gender order by total_revenue desc) as rn
		from ranked_orders)
			select Gender, Product_Category, total_revenue
            from ranked_category
            where rn <= 3
            order by Gender, total_revenue desc;
            
-- Top 3 product_category by revenue for each age_group.
with ranked_orders as (
	select Product_Category, Age_Group, round(sum(Total_Amount),2) as total_revenue,
    dense_rank() over (partition by Age_Group order by sum(Total_Amount) desc) as rn
    from ecommerce_cleaned
    group by Product_Category, Age_Group)
		select Product_Category, Age_Group, total_revenue
		from ranked_orders 
		where rn <= 3
		order by Age_Group;

-- Rank cities by revenue from mobile device users.
select City, Device_Type, round(sum(Total_Amount), 2) as total_revenue,
rank() over (order by sum(Total_Amount) desc) as rn
from ecommerce_cleaned
where Device_Type = 'Mobile'
group by City
order by rn;

-- Revenue generated by top 20% customers.
with customer_revenue as (
	select Customer_ID, sum(Total_Amount) as revenue
    from ecommerce_cleaned
    group by Customer_ID),
    ranked as ( 
		select Customer_ID, revenue, 
		ntile(5) over (order by revenue desc) as rn
		from customer_revenue)
			select round(sum(revenue),2) as top_20_percentage
			from ranked
			where rn = 1;
            
-- Identify cities where total revenue is above the overall average city revenue.
with city_revenue as (
	select City, round(sum(Total_Amount),2) as total_revenue
    from ecommerce_cleaned
    group by City) 
		select City, total_revenue
        from city_revenue
        where total_revenue > (select avg(total_revenue) as avg_revenue from city_revenue)
        order by total_revenue desc;
        
-- Average customer rating for each city and rank cities by it.
select City, round(avg(Customer_Rating),2) as avg_rating,
rank() over (order by round(avg(Customer_Rating),2) desc) as city_rank
from ecommerce_cleaned
group by City
order by city_rank;

-- KEY BUSINESS KPI
-- Percentage contribution of returning customers to total revenue
select
    round(
        count(distinct case when Is_Returning_Customer = 1 then Customer_ID end) * 100.0 /
        count(distinct Customer_ID),
        2
    ) as retention_percentage
from ecommerce_cleaned;